/**
 * Regenerate ground-truth fixtures (CCG v4.3 P28).
 *
 * Calls sampleAll() against the current user's ~/.claude/ + this repo, then
 * anonymizes paths and writes JSON to tests/fixtures/ground-truth/.
 *
 * Usage:
 *   pnpm regen-fixtures              # regen all
 *   pnpm regen-fixtures --dry-run    # print what would be written, don't touch disk
 *
 * After regen, manually inspect the diff: the goal is *representative* fixtures
 * (diverse hook matcher types, mixed user-invocable skills, both known and
 * unknown plugins). If your environment is too narrow, hand-edit before commit.
 */

import { writeFileSync, readFileSync, existsSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  sampleAll,
  sampleHookSchema,
  samplePluginList,
  sampleSkillList,
} from '../src/utils/ground-truth-sampler.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(__dirname, '..')
const FIXTURES_DIR = join(REPO_ROOT, 'tests', 'fixtures', 'ground-truth')

const HOME = homedir()
const DRY_RUN = process.argv.includes('--dry-run')

/**
 * Replace user-home-specific path segments with <HOME> placeholder.
 * Handles both forward and back slashes.
 */
function anonymize(value: unknown): unknown {
  if (typeof value === 'string') {
    // Normalize path separators then replace home prefix
    const normalized = value.replace(/\\/g, '/')
    const homeNormalized = HOME.replace(/\\/g, '/')
    return normalized.replace(homeNormalized, '<HOME>')
  }
  if (Array.isArray(value)) return value.map(anonymize)
  if (value && typeof value === 'object') {
    const out: Record<string, unknown> = {}
    for (const [k, v] of Object.entries(value)) out[k] = anonymize(v)
    return out
  }
  return value
}

function writeFixture(name: string, payload: unknown): void {
  const path = join(FIXTURES_DIR, name)
  const json = JSON.stringify(payload, null, 2) + '\n'
  if (DRY_RUN) {
    console.log(`[dry-run] would write ${path} (${json.length} bytes)`)
    return
  }
  writeFileSync(path, json, 'utf8')
  console.log(`✓ wrote ${path} (${json.length} bytes)`)
}

function regenInstalledPlugins(): void {
  const path = join(HOME, '.claude', 'plugins', 'installed_plugins.json')
  if (!existsSync(path)) {
    console.warn(`[skip] ${path} not found; keeping existing installed_plugins.sample.json`)
    return
  }
  const raw = JSON.parse(readFileSync(path, 'utf8'))
  writeFixture('installed_plugins.sample.json', anonymize(raw))
}

function regenSettings(): void {
  const path = join(HOME, '.claude', 'settings.json')
  if (!existsSync(path)) {
    console.warn(`[skip] ${path} not found; keeping existing settings.sample.json`)
    return
  }
  const raw = JSON.parse(readFileSync(path, 'utf8'))
  // Strip personal sections (env vars, model preferences) but keep hooks + permissions shape.
  const filtered = {
    $schema: raw.$schema,
    permissions: raw.permissions,
    hooks: raw.hooks,
  }
  writeFixture('settings.sample.json', anonymize(filtered))
}

function regenSkills(): void {
  const { skills, warnings } = sampleSkillList(HOME)
  if (warnings.length > 0) {
    console.warn(`[warn] sampleSkillList: ${warnings.join('; ')}`)
  }
  if (skills.length === 0) {
    console.warn(`[skip] no skills found under ~/.claude/skills/ccg/; keeping existing skills.sample.json`)
    return
  }
  // Limit to 13 representative entries: prefer mix of categories + invocable states.
  const byCategory = new Map<string, typeof skills>()
  for (const s of skills) {
    const cat = s.category ?? 'unknown'
    if (!byCategory.has(cat)) byCategory.set(cat, [])
    byCategory.get(cat)!.push(s)
  }
  const picked: typeof skills = []
  for (const list of byCategory.values()) {
    // Take up to 4 per category; ensure mix of invocable=true + false if possible
    const inv = list.filter(s => s.userInvocable).slice(0, 3)
    const notInv = list.filter(s => !s.userInvocable).slice(0, 2)
    picked.push(...inv, ...notInv)
  }
  const trimmed = picked.slice(0, 15)
  writeFixture('skills.sample.json', {
    _comment: 'Auto-regenerated by scripts/regen-fixtures.ts. Schema must match SkillInfo[] from src/utils/ground-truth-sampler.ts.',
    skills: anonymize(trimmed),
  })
}

function main(): void {
  if (!existsSync(FIXTURES_DIR)) {
    console.error(`fixtures dir not found: ${FIXTURES_DIR}`)
    process.exit(1)
  }
  console.log(`Regenerating fixtures into ${FIXTURES_DIR}${DRY_RUN ? ' (dry run)' : ''}`)
  console.log(`Source HOME: ${HOME}`)
  console.log('')

  regenInstalledPlugins()
  regenSettings()
  regenSkills()

  console.log('')
  console.log('Note: agent-summaries.sample.json is hand-curated (not regenerated)')
  console.log('  — edit by hand when subagent output schemas change.')
  console.log('')
  console.log('Done. Review diff before committing.')

  // Suppress unused-import warning when only one of the helpers is reached
  void sampleAll
  void samplePluginList
  void sampleHookSchema
}

main()
